export const GET_ADMISSION_STEP_INSTANCES = 'GET_ADMISSION_STEP_INSTANCES';
export const GET_ADMISSION_STEP_INSTANCES_COMPLETED =
    'GET_ADMISSION_STEP_INSTANCES_COMPLETED';
export const GET_ADMISSION_STEP_INSTANCES_FAILED =
    'GET_ADMISSION_STEP_INSTANCES_FAILED';

export const SET_SHOW_AGENT_TYPE_COMPLETE = "SET_SHOW_AGENT_TYPE_COMPLETE";
