// SSN Validation
export const VERIFY_SSN_UNIQUE = 'VERIFY_SSN_UNIQUE';

export const VERIFY_SSN_AND_NAME = 'VERIFY_SSN_AND_NAME';
export const VERIFY_SSN_AND_NAME_COUNTRY = 'VERIFY_SSN_AND_NAME_COUNTRY';
export const VERIFY_SSN_AND_NAME_COMPLETED = 'VERIFY_SSN_AND_NAME_COMPLETED';
export const VERIFY_SSN_AND_NAME_FAILED = 'VERIFY_SSN_AND_NAME_FAILED';

export const UPDATE_NAME = "UPDATE_NAME";

// Business Path
export const SELECT_BUSINESS_PATH = 'SELECT_BUSINESS_PATH';
export const SELECT_BUSINESS_PATH_COMPLETED = 'SELECT_BUSINESS_PATH_COMPLETED';
export const SELECT_BUSINESS_PATH_FAILED = 'SELECT_BUSINESS_PATH_FAILED';

export const CHANGE_BUSINESS_PATH = 'CHANGE_BUSINESS_PATH';
export const CHANGE_BUSINESS_PATH_LOCATION = 'CHANGE_BUSINESS_PATH_LOCATION';

// Register Individual
export const REGISTER_INDIVIDUAL = 'REGISTER_INDIVIDUAL';
export const REGISTER_INDIVIDUAL_COMPLETED = 'REGISTER_INDIVIDUAL_COMPLETED';
export const REGISTER_INDIVIDUAL_FAILED = 'REGISTER_INDIVIDUAL_FAILED';

export const REMOVE_REGISTER_INDIVIDUAL = 'REMOVE_REGISTER_INDIVIDUAL';
export const REMOVE_REGISTER_INDIVIDUAL_COMPLETED = 'REMOVE_REGISTER_INDIVIDUAL_COMPLETED';
export const REMOVE_REGISTER_INDIVIDUAL_FAILED = 'REMOVE_REGISTER_INDIVIDUAL_FAILED';

export const FINALIZE_REGISTER_INDIVIDUAL = 'FINALIZE_REGISTER_INDIVIDUAL';
export const FINALIZE_REGISTER_INDIVIDUAL_COMPLETED = 'FINALIZE_REGISTER_INDIVIDUAL_COMPLETED';
export const FINALIZE_REGISTER_INDIVIDUAL_FAILED = 'FINALIZE_REGISTER_INDIVIDUAL_FAILED';

// Register Business
export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
export const VERIFY_BUSINESS_ID = 'VERIFY_BUSINESS_ID';
export const REGISTER_BUSINESS_COMPLETED = 'REGISTER_BUSINESS_COMPLETED';
export const REGISTER_BUSINESS_FAILED = 'REGISTER_BUSINESS_FAILED';

// Validate GST/HST
export const VALIDATE_GSTHST_INIT = 'VALIDATE_GSTHST_INIT';
export const VALIDATE_GSTHST_COMPLETED = 'VALIDATE_GSTHST_COMPLETED';
export const VALIDATE_GSTHST_FAILED = 'VALIDATE_GSTHST_FAILED';



//Spring Verify GST
export const SPRING_VERIFY_GST = 'SPRING_VERIFY_GST';
export const SPRING_VERIFY_GST_COMPLETED = 'SPRING_VERIFY_GST_COMPLETED';
export const SPRING_VERIFY_GST_FAILED = 'SPRING_VERIFY_GST_FAILED';
export const SPRING_VERIFY_GST_API_FAILED = 'SPRING_VERIFY_GST_API_FAILED';

export const TOGGLE_IS_FETCHING_FLAG_FOR_GST = 'TOGGLE_IS_FETCHING_FLAG_FOR_GST';
export const CLEAR_REGISTER_BUSINESS_ERROR = 'CLEAR_REGISTER_BUSINESS_ERROR';

//SEC Verify
export const SEC_VERIFY = 'SEC_VERIFY';
export const SEC_VERIFY_COMPLETED = 'SEC_VERIFY_COMPLETED';
export const SEC_VERIFY_FAILED = 'SEC_VERIFY_FAILED';
export const SEC_VERIFY_API_FAILED = 'SEC_VERIFY_API_FAILED';

export const TOGGLE_IS_FETCHING_FLAG_FOR_SEC = 'TOGGLE_IS_FETCHING_FLAG_FOR_SEC';

//TIN Verify
export const TIN_VERIFY = 'TIN_VERIFY';
export const TIN_VERIFY_COMPLETED = 'TIN_VERIFY_COMPLETED';
export const TIN_VERIFY_FAILED = 'TIN_VERIFY_FAILED';
export const TIN_VERIFY_API_FAILED = 'TIN_VERIFY_API_FAILED';

export const TOGGLE_IS_FETCHING_FLAG_FOR_TIN = 'TOGGLE_IS_FETCHING_FLAG_FOR_TIN';

// 
export const VERIFY_FEIN_UNIQUE = 'VERIFY_FEIN_UNIQUE';



export const VERIFY_FEIN_AND_COMPANY_NAME = 'VERIFY_FEIN_AND_COMPANY_NAME';
export const VERIFY_FEIN_AND_COMPANY_NAME_COMPLETED = 'VERIFY_FEIN_AND_COMPANY_NAME_COMPLETED';
export const VERIFY_FEIN_AND_COMPANY_NAME_FAILED = 'VERIFY_FEIN_AND_COMPANY_NAME_FAILED';

export const GET_GST_HST = 'GET_GST_HST';
export const GET_GST_HST_COMPLETED = 'GET_GST_HST_COMPLETED';
export const GET_GST_HST_FAILED = 'GET_GST_HST_FAILED';

export const GET_TypeOfIncorporation = 'GET_TypeOfIncorporation';
export const GET_TypeOfIncorporation_COMPLETED = 'GET_TypeOfIncorporation_COMPLETED';
export const GET_TypeOfIncorporation_FAILED = 'GET_TypeOfIncorporation_FAILED';

export const REMOVE_REGISTER_BUSINESS = 'REMOVE_REGISTER_BUSINESS';
export const REMOVE_REGISTER_BUSINESS_COMPLETED = 'REMOVE_REGISTER_BUSINESS_COMPLETED';
export const REMOVE_REGISTER_BUSINESS_FAILED = 'REMOVE_REGISTER_BUSINESS_FAILED';

export const REMOVE_REGISTER_BUSINESS_FORM = 'REMOVE_REGISTER_BUSINESS_FORM';

export const FINALIZE_REGISTER_BUSINESS = 'FINALIZE_REGISTER_BUSINESS';
export const FINALIZE_REGISTER_BUSINESS_COMPLETED = 'FINALIZE_REGISTER_BUSINESS_COMPLETED';
export const FINALIZE_REGISTER_BUSINESS_FAILED = 'FINALIZE_REGISTER_BUSINESS_FAILED';

// Join Business
export const JOIN_BUSINESS = 'JOIN_BUSINESS';
export const JOIN_BUSINESS_COMPLETED = 'JOIN_BUSINESS_COMPLETED';
export const JOIN_BUSINESS_FAILED = 'JOIN_BUSINESS_FAILED';

export const GET_BUSINESS_BY_FEIN = 'GET_BUSINESS_BY_FEIN';
export const GET_BUSINESS_BY_FEIN_COMPLETED = 'GET_BUSINESS_BY_FEIN_COMPLETED';
export const GET_BUSINESS_BY_FEIN_FAILED = 'GET_BUSINESS_BY_FEIN_FAILED';

export const GET_BUSINESS_BY_ID = 'GET_BUSINESS_BY_ID';
export const GET_BUSINESS_BY_ID_COMPLETED = 'GET_BUSINESS_BY_ID_COMPLETED';
export const GET_BUSINESS_BY_ID_FAILED = 'GET_BUSINESS_BY_ID_FAILED';

export const GET_BUSINESSES_TO_JOIN = 'GET_BUSINESSES_TO_JOIN';
export const GET_BUSINESSES_TO_JOIN_COMPLETED = 'GET_BUSINESSES_TO_JOIN_COMPLETED';
export const GET_BUSINESSES_TO_JOIN_FAILED = 'GET_BUSINESSES_TO_JOIN_FAILED';

export const GET_JOIN_BUSINESS_STATUS = 'GET_JOIN_BUSINESS_STATUS';
export const GET_JOIN_BUSINESS_STATUS_COMPLETED = 'GET_JOIN_BUSINESS_STATUS_COMPLETED';
export const GET_JOIN_BUSINESS_STATUS_FAILED = 'GET_JOIN_BUSINESS_STATUS_FAILED';

export const SELECT_BUSINESS_TO_JOIN = 'SELECT_BUSINESS_TO_JOIN';

export const REMOVE_JOIN_BUSINESS = 'REMOVE_JOIN_BUSINESS';
export const REMOVE_JOIN_BUSINESS_COMPLETED = 'REMOVE_JOIN_BUSINESS_COMPLETED';
export const REMOVE_JOIN_BUSINESS_FAILED = 'REMOVE_JOIN_BUSINESS_FAILED';

// Agreements
export const SHOW_AGREEMENTS = 'SHOW_AGREEMENTS';
export const HIDE_AGREEMENTS = 'HIDE_AGREEMENTS';
export const SHOW_AGREEMENT_CONTENT = 'SHOW_AGREEMENT_CONTENT';
export const HIDE_AGREEMENT_CONTENT = 'HIDE_AGREEMENT_CONTENT';

//Media

export const GET_MEDIA = "GET_MEDIA";
export const GET_MEDIA_COMPLETED = "GET_MEDIA_COMPLETED";
export const GET_MEDIA_FAILED = "GET_MEDIA_FAILED";

//Screening Assessment
export const SCREENINGASSESSMENT_REQUIRED = "SCREENINGASSESSMENT_REQUIRED";
export const SET_SCREENINGASSESSMENT_REQUIRED = "SET_SCREENINGASSESSMENT_REQUIRED";
export const SCREENINGASSESSMENT_REFRESH = "SCREENINGASSESSMENT_REFRESH";
