export const GET_AGREEMENT_TEMPLATES = 'GET_AGREEMENT_TEMPLATES';
export const GET_AGREEMENT_TEMPLATES_COMPLETED =
  'GET_AGREEMENT_TEMPLATES_COMPLETED';
export const GET_AGREEMENT_TEMPLATES_FAILED = 'GET_AGREEMENT_TEMPLATES_FAILED';

export const GET_AGREEMENT_TEMPLATE_CONTENT = 'GET_AGREEMENT_TEMPLATE_CONTENT';
export const GET_AGREEMENT_TEMPLATE_CONTENT_COMPLETED =
  'GET_AGREEMENT_TEMPLATE_CONTENT_COMPLETED';
export const GET_AGREEMENT_TEMPLATE_CONTENT_FAILED =
  'GET_AGREEMENT_TEMPLATE_CONTENT_FAILED';

export const SIGN_AGREEMENT = 'SIGN_AGREEMENT';
export const SIGN_AGREEMENT_COMPLETED = 'SIGN_AGREEMENT_COMPLETED';
export const SIGN_AGREEMENT_FAILED = 'SIGN_AGREEMENT_FAILED';
export const IS_NEXT_CLICKED='IS_NEXT_CLICKED';

//Conga integration
export const GET_SIGN_URL='GET_SIGN_URL'
export const GET_SIGN_URL_SUCCESS='GET_SIGN_URL_SUCCESS'
export const GET_SIGN_URL_FAIL='GET_SIGN_URL_FAIL'

//Check the status of signing agreement URL

export const CheckSignStatus="CheckSignStatus"
export const CheckSignStatusComplete="CheckSignStatusComplete"
export const CheckSignStatusError="CheckSignStatusError"


//Clear TransactionId if any error

export const CLEAR_TRANSACTION_ID="CLEAR_TRANSACTION_ID"
