export const LOGIN_REDIRECT = 'LOGIN_REDIRECT';
export const LOGOUT_REDIRECT = 'LOGOUT_REDIRECT';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_COMPLETED = 'LOGIN_USER_COMPLETED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_COMPLETED = 'LOGOUT_USER_COMPLETED';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_COMPLETED = 'FORGOT_PASSWORD_COMPLETED';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const FORGOT_USERNAME = 'FORGOT_USERNAME';
export const FORGOT_USERNAME_COMPLETED = 'FORGOT_USERNAME_COMPLETED';
export const FORGOT_USERNAME_FAILED = 'FORGOT_USERNAME_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_COMPLETED = 'RESET_PASSWORD_COMPLETED';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const VERIFY_CAPTCHA = 'VERIFY_CAPTCHA';
export const VERIFY_CAPTCHA_COMPLETED = 'VERIFY_CAPTCHA_COMPLETED';
export const VERIFY_CAPTCHA_FAILED = 'VERIFY_CAPTCHA_FAILED';
