export const REGISTER_REDIRECT = "REGISTER_REDIRECT";

export const CREATE_AGENT_PROFILE = "CREATE_AGENT_PROFILE";
export const CREATE_AGENT_PROFILE_COMPLETED = "CREATE_AGENT_PROFILE_COMPLETED";
export const CREATE_AGENT_PROFILE_FAILED = "CREATE_AGENT_PROFILE_FAILED";

export const GET_AGENT_PROFILE = "GET_AGENT_PROFILE";
export const GET_AGENT_PROFILE_COMPLETED = "GET_AGENT_PROFILE_COMPLETED";
export const GET_AGENT_PROFILE_FAILED = "GET_AGENT_PROFILE_FAILED";

export const GET_USER_COUNTRY = "GET_USER_COUNTRY";
export const GET_USER_COUNTRY_COMPLETED = "GET_USER_COUNTRY_COMPLETED";
export const GET_USER_COUNTRY_FAILED = "GET_USER_COUNTRY_FAILED";

export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_COMPLETED = "GET_COUNTRIES_COMPLETED";
export const GET_COUNTRIES_FAILED = "GET_COUNTRIES_FAILED";

export const GET_STATES = "GET_STATES";
export const GET_STATES_COMPLETED = "GET_STATES_COMPLETED";
export const GET_STATES_FAILED = "GET_STATES_FAILED";

export const GET_PROVINCES = "GET_PROVINCES";
export const GET_PROVINCES_COMPLETED = "GET_PROVINCES_COMPLETED";
export const GET_PROVINCES_FAILED = "GET_PROVINCES_FAILED";

export const GET_LEGACY_ID_COMPLETE = "GET_LEGACY_ID_COMPLETE";
export const GET_REFERRAL_USER = "GET_REFERRAL_USER";
export const GET_REFERRAL_USER_SUCCESS = "GET_REFERRAL_USER_SUCCESS";
export const GET_REFERRAL_USER_FAILURE = "GET_REFERRAL_USER_FAILURE";
export const PUT_REFERRAL_USER = "PUT_REFERRAL_USER";
export const PUT_JM_USER_NAME_DOB = "PUT_JM_USER_NAME_DOB"

export const GET_PARISHES = "GET_PARISHES";
export const GET_PARISHES_COMPLETED = "GET_PARISHES_COMPLETED";
export const GET_PARISHES_FAILED = "GET_PARISHES_FAILED";

export const PUT_PARISH_DATA = "PUT_PARISH_DATA"
export const PUT_PARISH_DATA_COMPLETED = "PUT_PARISH_DATA_COMPLETED"
export const PUT_PARISH_DATA_FAILURE = "PUT_PARISH_DATA_FAILURE"

export const CHECK_IF_JM_CONSENT_SIGNED = "CHECK_IF_JM_CONSENT_SIGNED"
export const CHECK_IF_JM_CONSENT_SIGNED_SUCCESS = "CHECK_IF_JM_CONSENT_SIGNED_SUCCESS"

export const DECLINE_JM_CONSENT = "DECLINE_JM_CONSENT"

export const UPDATE_LANGUAGE_PREFERENCE = 'UPDATE_LANGUAGE_PREFERENCE';
