export const VALIDATE_PHONE = 'VALIDATE_PHONE';
export const VALIDATE_PHONE_COMPLETED = 'VALIDATE_PHONE_COMPLETED';
export const VALIDATE_PHONE_FAILED = 'VALIDATE_PHONE_FAILED';

export const RESEND_PHONE_VALIDATION_CODE = 'RESEND_PHONE_VALIDATION_CODE';
export const RESEND_PHONE_VALIDATION_CODE_COMPLETED =
  'RESEND_PHONE_VALIDATION_CODE_COMPLETED';
export const RESEND_PHONE_VALIDATION_CODE_FAILED =
  'RESEND_PHONE_VALIDATION_CODE_FAILED';

export const UPDATE_MOBILE_PHONE = 'UPDATE_MOBILE_PHONE';
export const UPDATE_MOBILE_PHONE_COMPLETED = 'UPDATE_MOBILE_PHONE_COMPLETED';
export const UPDATE_MOBILE_PHONE_FAILED = 'UPDATE_MOBILE_PHONE_FAILED';

export const CANCEL_MOBILE_PHONE = 'CANCEL_MOBILE_PHONE';
export const EDIT_MOBILE_PHONE = 'EDIT_MOBILE_PHONE';

export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
export const VALIDATE_EMAIL_COMPLETED = 'VALIDATE_EMAIL_COMPLETED';
export const VALIDATE_EMAIL_FAILED = 'VALIDATE_EMAIL_FAILED';

export const RESEND_EMAIL_VALIDATION_CODE = 'RESEND_EMAIL_VALIDATION_CODE';
export const RESEND_EMAIL_VALIDATION_CODE_COMPLETED =
  'RESEND_EMAIL_VALIDATION_CODE_COMPLETED';
export const RESEND_EMAIL_VALIDATION_CODE_FAILED =
  'RESEND_EMAIL_VALIDATION_CODE_FAILED';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_COMPLETED = 'UPDATE_EMAIL_COMPLETED';
export const UPDATE_EMAIL_FAILED = 'UPDATE_EMAIL_FAILED';

export const CANCEL_EMAIL = 'CANCEL_EMAIL';
export const EDIT_EMAIL = 'EDIT_EMAIL';
