export const GENERATE_SELF_PACED_LINK = "GENERATE_SELF_PACED_LINK";
export const GENERATE_VIRTUAL_CLASSROOM_LINK = "GENERATE_VIRTUAL_CLASSROOM_LINK";
export const GENERATE_CROWD_HUB_LINK = "GENERATE_CROWD_HUB_LINK"
export const GENERATE_KNOWLEDGE_ZONE_LINK = "GENERATE_KNOWLEDGE_ZONE_LINK"
export const GENERATE_spotify_KNOWLEDGE_ZONE_LINK = "GENERATE_spotify_KNOWLEDGE_ZONE_LINK"
export const GENERATE_CHAT_ROOM_LINK = "GENERATE_CHAT_ROOM_LINK"
export const GENERATE_INTERVIEW_IQ_LINK = "GENERATE_INTERVIEW_IQ_LINK"
export const GENERATE_VOICE_LINK = "GENERATE_VOICE_LINK"
export const GENERATE_PROGRAM_LINK = "GENERATE_PROGRAM_LINK"
export const GENERATE_ABSORB_LMS_LINK = "GENERATE_ABSORB_LMS_LINK";

export const OPEN_Starmatic = "OPEN_Starmatic"

export const OPEN_BROSWER_LINK = "OPEN_BROSWER_LINK"
export const OPEN_BROSWER_LINK_NEW_TAB = "OPEN_BROSWER_LINK_NEW_TAB"
export const OPEN_BROSWER_LINK_NEW_WINDOW = "OPEN_BROSWER_LINK_NEW_WINDOW"
export const OPEN_BROWSER_POST_NEW_TAB = "OPEN_BROWSER_POST_NEW_TAB"

export const SET_RESULTS = "SET_RESULTS"
export const GENERATE_VA_LINK = "GENERATE_VA_LINK"

export const CHECK_spotify_KNOWLEDGE_ZONE_LINK = "CHECK_spotify_KNOWLEDGE_ZONE_LINK"
export const SET_spotify_KNOWLEDGE_ZONE_LINK = "SET_spotify_KNOWLEDGE_ZONE_LINK"

export const GENERATE_SCREENINGASSESSMENT_LINK = "GENERATE_SCREENINGASSESSMENT_LINK"
export const GENERATE_LANGUAGEIQ_LINK = "GENERATE_LANGUAGEIQ_LINK"
export const SET_IS_SCREENINGURL_GENERATED="SET_IS_SCREENINGURL_GENERATED"
export const SET_TO_INITIAL="SET_TO_INITIAL"
export const GENERATE_FINGERPRINT_LINK = "GENERATE_FINGERPRINT_LINK"


export const START_PCSCAN = "START_PCSCAN";
export const CLEAR_PCSCAN = "CLEAR_PCSCAN";
export const START_PHOTOID_VERIFICATION = "START_PHOTOID_VERIFICATION";
export const PCSCAN_COMPLETED = "PCSCAN_COMPLETED";
