export const APPLICATION_INSIGHTS_TRACK_EVENT = "APPLICATION_INSIGHTS_TRACK_EVENT";
export const APPLICATION_INSIGHTS_TRACK_ERROR = "APPLICATION_INSIGHTS_TRACK_ERROR";
export const APPLICATION_INSIGHTS_TRACK_TRACE = "APPLICATION_INSIGHTS_TRACK_TRACE";
