
export const InitializeEnrollmentPrerequisitesPage = "InitializeEnrollmentPrerequisitesPage";
export const InitializeEnrollmentPrerequisitesPageComplete = "InitializeEnrollmentPrerequisitesPageComplete";
export const InitializeEnrollmentPrerequisitesPageError = "InitializeEnrollmentPrerequisitesPageError";
