
export const ENROLLED_PROGRAM_GET_BY_AGENT = "ENROLLED_PROGRAM_GET_BY_AGENT";
export const ENROLLED_PROGRAM_GET_BY_AGENT_COMPLETE = "ENROLLED_PROGRAM_GET_BY_AGENT_COMPLETE";
export const ENROLLED_PROGRAM_GET_BY_AGENT_ERROR = "ENROLLED_PROGRAM_GET_BY_AGENT_ERROR";


//Cancel Class
export const STAGE_CANCEL_ENROLLMENT = "STAGE_CANCEL_ENROLLMENT";
export const CANCEL_STAGED_ENROLLMENT = "CANCEL_STAGED_ENROLLMENT";
export const CANCEL_ENROLLMENT_COMPLETE = "CANCEL_ENROLLMENT_COMPLETE";
export const CANCEL_ENROLLMENT_ERROR = "CANCEL_ENROLLMENT_ERROR";

//Drop Class
export const DROP_STAGED_ENROLLMENT = "DROP_STAGED_ENROLLMENT";
export const DROP_ENROLLMENT_COMPLETE = "DROP_ENROLLMENT_COMPLETE";
export const DROP_ENROLLMENT_ERROR = "DROP_ENROLLMENT_ERROR";
export const STAGE_DROP_ENROLLMENT = "Stage Drop Enrollment";

export const CANCEL_ENROLLMENT_REFRESH = "CANCEL_ENROLLMENT_REFRESH";

export const GET_DROPSTATUSREASON = "GET_DROPSTATUSREASON";
export const GET_DROPSTATUSREASON_COMPLETED = 'GET_DROPSTATUSREASON_COMPLETED';
export const GET_DROPSTATUSREASON_ERROR = 'GET_DROPSTATUSREASON_ERROR';

//Reschedule Class
export const RESCHEDULE_CLASS = "RESCHEDULE_CLASS"
export const RESCHEDULE_CLASS_COMPLETE = "RESCHEDULE_CLASS_COMPLETE"
export const RESCHEDULE_CLASS_ERROR = "RESCHEDULE_CLASS_ERROR"
export const STAGE_CLASS_TORESCHEDULE = "STATE_CLASS_TORESCHEDULE"

export const ELIGIBLITY_CHECK = "ELIGIBLITY_CHECK"
export const ELIGIBLITY_CHECK_COMPLETE = "ELIGIBLITY_CHECK_COMPLETE"
export const ELIGIBLITY_CHECK_ERROR = "ELIGIBLITY_CHECK_ERROR"
export const CLEAR_ELIGIBLITY_CHECK = "CLEAR_ELIGIBLITY_CHECK"

