export const SET_HEADER_VISIBLE = "SET_HEADER_VISIBLE";
export const SET_HEADER_INVISIBLE = "SET_HEADER_INVISIBLE";
export const SET_HEADER_VISIBLE_COMPLETE = "SET_HEADER_VISIBLE_COMPLETE";
export const SET_HEADER_INVISIBLE_COMPLETE = "SET_HEADER_INVISIBLE_COMPLETE";
