export const FETCH_METRICS = "FETCH_METRICS";
export const FETCH_METRICS_COMPLETE = "FETCH_METRICS_COMPLETE";
export const FETCH_METRICS_ERROR = "FETCH_METRICS_ERROR";
export const FETCH_METRICS_FOR_PROGRAM = "FETCH_METRICS_FOR_PROGRAM";
