export const GET_PREFERENCES = 'GET_PREFERENCES ';
export const GET_PREFERENCES_COMPLETED = 'GET_PREFERENCES_COMPLETED';
export const GET_PREFERENCES_FAILED =  'GET_PREFERENCES_FAILED';

export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES ';
export const UPDATE_PREFERENCES_COMPLETED = 'UPDATE_PREFERENCES_COMPLETED';
export const UPDATE_PREFERENCES_FAILED =  'UPDATE_PREFERENCES_FAILED';

